# Some dummy value cause not need for 1st stage
#key: val

# For 2nd stage
AUGMENTATION: True
IMAGE_SIZE:  [256, 256, 3]
BATCH_SIZE: 16
EPOCHS: 1 #100
LEARNING_RATE: 0.0002
GENERATOR_FILTERS: 64
DISCRIMINATOR_FILTERS: 64
USE_BIAS: False
DROPOUT_RATE: 0.5

INCLUDE_TOP: False
CLASSES: 4
WEIGHTS: imagenet

BETA1: 0.5
LAMBDA_CYCLE: 10
LAMBDA_IDENTITY: 0.5
SAVE_INTERVAL: 5

EVAL_SAMPLES: 32     # Number of samples to evaluate
SAVE_FORMAT: "png"   # Format for saving generated images